version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: .docker/nest/Dockerfile
      target: base
    container_name: maratona_5_nest
    image: yurikoster1/maratona_5_nest:dev
    command: ["npm", "run", "start:dev"]
#    command: ["/bin/bash"]
    volumes:
      - ./app:/home/node/app
    ports:
    - 8082:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  keycloak:
    build:
      context: .docker/keycloak
      dockerfile: Dockerfile

    container_name: maratona_5_keycloak
    image: yurikoster1/maratona_5_keycloak
    environment:
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}'
      - 'DB_VENDOR=mysql'
      - 'DB_ADDR=db'
      - 'DB_PORT=3306'
      - 'DB_DATABASE=keycloak'
      - 'DB_SCHEMA=keycloak'
      - 'DB_USER=root'
      - 'DB_PASSWORD=root'
    ports:
    - 8080:8080

  db:
    build:
      context: ./.docker/mysql
    container_name: maratona_5_db
    image: yurikoster1/maratona_5_db
    restart: unless-stopped
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root