version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: .docker/nest/Dockerfile
      target: ci
    container_name: maratona_5_nest
    image: yurikoster1/maratona_5_nest:ci
    entrypoint: 'dockerize -wait tcp://db:3306 -timeout 400s -wait http://keycloak:8080 -timeout 400s '
    command: ["npm", "run", "start"]
    depends_on:
      - keycloak
      - db


  keycloak:
    build:
      context: .docker/keycloak
      dockerfile: Dockerfile
    container_name: maratona_5_keycloak
    environment:
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=123456'
      - 'DB_VENDOR=mysql'
      - 'DB_ADDR=db'
      - 'DB_PORT=3306'
      - 'DB_DATABASE=keycloak'
      - 'DB_SCHEMA=keycloak'
      - 'DB_USER=root'
      - 'DB_PASSWORD=root'
    ports:
    - 8080:8080
    depends_on:
      - db

  db:
    build:
      context: ./.docker/mysql
    container_name: maratona_5_db
    image: yurikoster1/maratona_5_db
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root