name: CI
on: ['pull_request']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker-compose-ci.yml up -d
      - run: docker logs maratona_5_nest
      - run: docker logs maratona_5_keycloak
      - run: docker logs maratona_5_db
      - run: docker exec maratona_5_nest npm run test
      - run: docker exec maratona_5_nest dockerize -timeout=300s -wait=http://localhost:3000
      - run: docker logs maratona_5_nest
      - run: docker exec maratona_5_nest npm run test
